version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - db_data:/data/db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  
  sensors_api:
    build: .
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - 'mongodb'
    ports:
      - "127.0.0.1:3000:3000"
    env_file: .env
    environment:
      - APP_HOSTNAME=$APP_HOSTNAME
      - APP_PORT=$APP_PORT
      - APP_PATH=$APP_PATH
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DBNAME=$MONGO_DBNAME

volumes:
  db_data: